# Generated by Django 5.2.12 on 2026-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_input', models.TextField(help_text='The exact text entered by the user.')),
                ('final_prompt', models.TextField(help_text='The optimized prompt sent to the local model.')),
                ('mode', models.CharField(choices=[('type', 'Type to Image'), ('script', 'Script to Image')], max_length=20)),
                ('style', models.CharField(blank=True, max_length=80)),
                ('width', models.PositiveIntegerField(default=512)),
                ('height', models.PositiveIntegerField(default=512)),
                ('inference_steps', models.PositiveIntegerField(default=25)),
                ('guidance_scale', models.FloatField(default=7.5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
